import random

quotes = [
     "Be yourself; everyone else is already taken. – Oscar Wilde",
    "Two things are infinite: the universe and human stupidity; and I'm not sure about the universe. – Albert Einstein",
    "So many books, so little time. – Frank Zappa",
    "A room without books is like a body without a soul. – Marcus Tullius Cicero",
    "In three words I can sum up everything I've learned about life: it goes on. – Robert Frost",
    "If you tell the truth, you don't have to remember anything. – Mark Twain",
    "Be the change that you wish to see in the world. – Mahatma Gandhi",
    "If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals. – J.K. Rowling",
    "Don’t walk in front of me… I may not follow; Don’t walk behind me… I may not lead; Walk beside me… just be my friend. – Albert Camus",
    "No one can make you feel inferior without your consent. – Eleanor Roosevelt",
    "Live as if you were to die tomorrow. Learn as if you were to live forever. – Mahatma Gandhi",
    "I have not failed. I've just found 10,000 ways that won't work. – Thomas A. Edison",
    "It is never too late to be what you might have been. – George Eliot",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. – Winston S. Churchill",
    "We accept the love we think we deserve. – Stephen Chbosky",
    "It does not do to dwell on dreams and forget to live. – J.K. Rowling",
    "Everything you can imagine is real. – Pablo Picasso",
    "To live is the rarest thing in the world. Most people exist, that is all. – Oscar Wilde",
    "Without music, life would be a mistake. – Friedrich Nietzsche",
    "We are all in the gutter, but some of us are looking at the stars. – Oscar Wilde",
    "Life isn't about finding yourself. Life is about creating yourself. – George Bernard Shaw",
    "Happiness is not something ready made. It comes from your own actions. – Dalai Lama",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. – Ralph Waldo Emerson",
    "If you judge people, you have no time to love them. – Mother Teresa",
    "It is our choices, that show what we truly are, far more than our abilities. – J.K. Rowling",
    "Peace begins with a smile. – Mother Teresa",
    "The only way to do great work is to love what you do. – Steve Jobs",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. – Ralph Waldo Emerson",
    "Dream big and dare to fail. – Norman Vaughan",
    "The best way out is always through. – Robert Frost",
    "Injustice anywhere is a threat to justice everywhere. – Martin Luther King Jr.",
    "The journey of a thousand miles begins with one step. – Lao Tzu",
    "Believe you can and you're halfway there. – Theodore Roosevelt",
    "Turn your wounds into wisdom. – Oprah Winfrey",
    "Change your thoughts and you change your world. – Norman Vincent Peale",
    "The only true wisdom is in knowing you know nothing. – Socrates",
    "Strive not to be a success, but rather to be of value. – Albert Einstein",
    "I came, I saw, I conquered. – Julius Caesar",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment. – Ralph Waldo Emerson",
    "That which does not kill us makes us stronger. – Friedrich Nietzsche",
    "Do what you can, with what you have, where you are. – Theodore Roosevelt",
    "You must be the change you wish to see in the world. – Mahatma Gandhi",
    "In the end, we will remember not the words of our enemies, but the silence of our friends. – Martin Luther King Jr.",
    "Imagination is more important than knowledge. – Albert Einstein",
    "The best way to predict the future is to invent it. – Alan Kay",
    "It's not whether you get knocked down, it's whether you get up. – Vince Lombardi",
    "You miss 100% of the shots you don't take. – Wayne Gretzky",
    "To succeed in life, you need two things: ignorance and confidence. – Mark Twain",
    "The mind is everything. What you think you become. – Buddha",
    "Life is really simple, but we insist on making it complicated. – Confucius",
    "Act as if what you do makes a difference. It does. – William James",
    "Life is 10% what happens to us and 90% how we react to it. – Charles R. Swindoll",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. – Zig Ziglar",
    "You are never too old to set another goal or to dream a new dream. – C.S. Lewis",
    "Life is like riding a bicycle. To keep your balance, you must keep moving. – Albert Einstein",
    "Only a life lived for others is a life worthwhile. – Albert Einstein",
    "Keep your face always toward the sunshine—and shadows will fall behind you. – Walt Whitman",
    "Try to be a rainbow in someone's cloud. – Maya Angelou",
    "Limit your 'always' and your 'nevers.' – Amy Poehler",
    "Nothing is impossible. The word itself says ‘I’m possible!’ – Audrey Hepburn",
    "You define your own life. Don’t let other people write your script. – Oprah Winfrey",
    "You can be everything. You can be the infinite amount of things that people are. – Kesha",
    "What lies behind you and what lies in front of you, pales in comparison to what lies inside of you. – Ralph Waldo Emerson",
    "Whoever is happy will make others happy too. – Anne Frank",
    "Do not allow people to dim your shine because they are blinded. Tell them to put on some sunglasses. – Lady Gaga",
    "Try to be a rainbow in someone's cloud. – Maya Angelou",
    "When you have a dream, you've got to grab it and never let go. – Carol Burnett",
    "Nothing will work unless you do. – Maya Angelou",
    "If you look at what you have in life, you'll always have more. – Oprah Winfrey",
    "The bad news is time flies. The good news is you’re the pilot. – Michael Altshuler",
    "Never bend your head. Always hold it high. Look the world straight in the eye. – Helen Keller",
    "Let us make our future now, and let us make our dreams tomorrow’s reality. – Malala Yousafzai",
    "It always seems impossible until it’s done. – Nelson Mandela",
    "What you do makes a difference, and you have to decide what kind of difference you want to make. – Jane Goodall",
    "It’s not the years in your life that count. It’s the life in your years. – Abraham Lincoln",
    "You do not find the happy life. You make it. – Camilla Eyring Kimball",
    "The purpose of our lives is to be happy. – Dalai Lama",
    "Doubt kills more dreams than failure ever will. – Suzy Kassem",
    "Success is getting what you want, happiness is wanting what you get. – W.P. Kinsella",
    "Sometimes you will never know the value of a moment until it becomes a memory. – Dr. Seuss",
    "It is never too late to be what you might have been. – George Eliot",
    "You only live once, but if you do it right, once is enough. – Mae West",
    "To love and be loved is to feel the sun from both sides. – David Viscott",
    "The way to get started is to quit talking and begin doing. – Walt Disney",
    "Don’t wait. The time will never be just right. – Napoleon Hill",
    "You must do the things you think you cannot do. – Eleanor Roosevelt",
    "It takes courage to grow up and become who you really are. – E.E. Cummings",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart. – Roy T. Bennett",
    "Believe in yourself. You are braver than you think, more talented than you know, and capable of more than you imagine. – Roy T. Bennett",
    "Be mindful. Be grateful. Be positive. Be true. Be kind. – Roy T. Bennett",
    "Pain is inevitable. Suffering is optional. – Haruki Murakami",
    "The only limit to our realization of tomorrow is our doubts of today. – Franklin D. Roosevelt",
    "A person who never made a mistake never tried anything new. – Albert Einstein",
    "Be faithful to that which exists within yourself. – André Gide",
    "The future belongs to those who believe in the beauty of their dreams. – Eleanor Roosevelt",
    "We must be willing to let go of the life we planned so as to have the life that is waiting for us. – Joseph Campbell",
    "Life changes very quickly, in a very positive way, if you let it. – Lindsey Vonn",
    "Keep your eyes on the stars and your feet on the ground. – Theodore Roosevelt"
]

print(random.choice(quotes))
